spring.application.name=busi-api
spring.config.import=optional:file:.env[.properties],optional:file:./busi-api/.env[.properties]

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/busi}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=busiinc2025@gmail.com
spring.mail.password=qpjzzcjmezwfjhss
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

app.mail.contact.recipient=${MAIL_CONTACT_RECIPIENT:${spring.mail.username}}
app.mail.contact.from=${MAIL_CONTACT_FROM:${spring.mail.username}}
server.port=8080